### ISSUE TITLE
Report K's (number of studies)

### ISSUE THREAD

**Issue by JGurevitch** [gdietz/OpenMEE#152]
Report K's in all output.

**Comment by gdietz** [comment]
Dealt with this by always displaying the 'k' 'additional value' regardless of whether 'additional values' is selected in the preferences window. If 'additional values' is not selected, the "Additional Values" tree item is not created in the results window nav area and k is listed as a regular text output.

**Comment by JGurevitch** [comment]
Very good. I saw this in the output, it is a good solution.

On Sun, Jan 25, 2015 at 9:35 PM, George Dietz <notifications@github.com>
wrote:

> Dealt with this by always displaying the 'k' 'additional value' regardless
> of whether 'additional values' is selected in the preferences window. If
> 'additional values' is not selected, the "Additional Values" tree item is
> not created in the results window nav area and k is listed as a regular
> text output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/152#issuecomment-71408008>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
