### ISSUE TITLE
Fix output printing (text)

### ISSUE THREAD

**Issue by bwallace** [gdietz/OpenMEE#160]
See 11/22 email from Jessica ("Persistent problem with write-over of text") for description and sample dataset with which to reproduce.

**Comment by gdietz** [comment]
This is weird. I suspect it has something to do with the positioning of the QTextItems relative to the parent scene's coordinate system.

**Comment by gdietz** [comment]
This seems to happen when the output text is super long. This might be a problem with Qt itself. However, we might try to fix it by calling a re-jiggling function (via QTimer::singleShot) that would be called after all the items have been added to the scene and some nominal short time has passed that would rearrange the items. This is super hacky and bad though.

**Comment by JGurevitch** [comment]
Would there be a way of breaking up the output so that it gets output in separate batches, so it's not so long?

**Comment by dwaring87** [comment]
I just asked Jessica for her example dataset to replicate this, but I think I came across this issue using this dataset: [gur_hed.ome](https://www.dropbox.com/s/jollctvaayxyxwi/gur_hed.ome?dl=0) in the results of a cumulative MA (the text of different results sections was overlapping).

I only had this problem on Windows, everything was displayed properly on OS X.  Probably related: the Windows output had twice as many newlines in between the study rows in the summary (4 sets of ```\r\n``` while on OS X there were only two sets of ```\n```).  When manually replacing the 4 sets of newlines with just 2, the output printed correctly.

It does look like ```QGraphicsTextItem``` isn't properly calculating it's own height (maybe the extra newlines aren't being accounted for?).  If you use ```QGraphicsSimpleTextItem``` in place of ```QGraphicsTextItem``` the output is displayed properly but you lose the ability to copy the text from the results window.

As a workaround for still using ```QGraphicsTextItem``` you can set its text as HTML with all of its newlines replaced with ```<br />``` tags and wrapping it in ```<pre></pre>``` tags to keep the formatting.  The height seems to be properly calculated in this case for whatever reason.

**Comment by gdietz** [comment]
I had this problem in OSX as well using Jessica's example dataset when running a meta regression and using sp plant as a covariate. Your HTML idea is intriguing and would certainly be cleaner than reshuffling all the items after they're displayed. however if we use pre tags, we'll lose the pretty font since it will use a fixed width font instead. Also, we shouldn't need br tags within a pre block.

**Comment by gdietz** [comment]
fix is done, you can test it with [Correa2_dataset.ome](https://www.dropbox.com/s/c4lm60d6qphk3ru/Correa2_dataset.ome?dl=0)
