### ISSUE TITLE
Make a new logo

### ISSUE THREAD

**Issue by gdietz** [gdietz/OpenMEE#161]

**Comment by JGurevitch** [comment]
Yeah! We need a logo! The one on the left is too square and clunky. What does it mean? Of course, it doesn't have to be in Chinese..... I do like the basic idea of our current (illegal) logo but it may be overly straight and doesn't mean much (it's not real Chinese calligraphy, it lacks the grace of real characters). I like the green stuff on top, though.

**Comment by gdietz** [comment]
What about something like a green circle (algae colored) with a small forest plot inside? I found this https://m1.behance.net/rendition/modules/23671963/disp/f9e4bc0c65914b4046c44df476e0cb4e.png

and http://www.nhm.ac.uk/resources-rx/images/1013/volvox-aureus-green-alga_32106_1.jpg
which are both pretty neat looking.

**Comment by JGurevitch** [comment]
I don't understand--yes, volvox are cool, but what do they (or the circles
in the circles) have to do with OpenMEE, or meta-analysis? I may not be
understanding your idea.

On Sun, Feb 8, 2015 at 9:21 PM, George Dietz <notifications@github.com>
wrote:

> What about something like a green circle (algae colored) with a small
> forest plot inside? I found this
> https://m1.behance.net/rendition/modules/23671963/disp/f9e4bc0c65914b4046c44df476e0cb4e.png
>
> and
> http://www.nhm.ac.uk/resources-rx/images/1013/volvox-aureus-green-alga_32106_1.jpg
> which are both pretty neat looking.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/161#issuecomment-73448597>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bwallace** [comment]
It's like algae! I like it, anyway...

**Comment by JGurevitch** [comment]
So what's wrong with algae? What would sushi be without it?

On Wed, Feb 18, 2015 at 5:48 PM, byron wallace <notifications@github.com>
wrote:

> It's like algae! I like it, anyway...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/161#issuecomment-74965323>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
