### ISSUE TITLE
Proportion effect sizes

### ISSUE THREAD

**Issue by JGurevitch** [gdietz/OpenMEE#162]
I am working with someone who is using arsin square root proportions as her effect size. It is nice that this is available in OpenMEE as an effect size, but it doesn't make sense. She has data on the proportion of total municipal waste that is food waste. So, she has 2 numbers: total tonnes of waste, tonnes of food waste, and sample size, and wants to calculate the arcsin square root proportion. OpenMEE thinks she has a 2X2 contingency table (say what?) and then # events and sample size. This makes no sense to me. It would be nice if it actually did allow one to calculate proportions, the arcsin sq rt transformation, and then back transform the outcomes.

**Comment by bwallace** [comment]
Hmm I'm not sure that this is specific enough as stated. What do you mean
OpenMEE "thinks" she has a contingency table? Can you please provide (1)
the dataset in question, (2) the exact steps taken to reproduce the
behavior in question, and (3) the expected behavior (in contrast to what
occurs)? This way we can reproduce and address the issue. Thanks!

On Sun, Jan 4, 2015 at 8:14 PM, JGurevitch <notifications@github.com> wrote:

> I am working with someone who is using arsin square root proportions as
> her effect size. It is nice that this is available in OpenMEE as an effect
> size, but it doesn't make sense. She has data on the proportion of total
> municipal waste that is food waste. So, she has 2 numbers: total tonnes of
> waste, tonnes of food waste, and sample size, and wants to calculate the
> arcsin square root proportion. OpenMEE thinks she has a 2X2 contingency
> table (say what?) and then # events and sample size. This makes no sense to
> me. It would be nice if it actually did allow one to calculate proportions,
> the arcsin sq rt transformation, and then back transform the outcomes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/162>.
>



-- 
byron

**Comment by JGurevitch** [comment]
Oh, I'm very anthropomorphic about the intentions of software!
Data are something of this sort:
[study]    [pounds of food waste]   [pounds of total waste]  [other
moderators]
Where the things in brackets are columns, and the rows are the values for
each study.
Open OpenMEE
Go to Effect Size, Calculate Effect Size
the only way to choose Arcsin sqrt proportion is to choose "2X2 contingency
table", so, if you choose 2x2 contingency table and then choose Arcsin sqrt
proportion, it asks you to choose "number of events" and "sample size". It
does not ask you to choose one number for the numerator of the proportion,
and another value for the denominator of the proportion (both continuous
values, not counts), which is what is needed to calculate a proportion. I
don't know what number of events is.
Is this clearer?

On Sun, Jan 4, 2015 at 10:12 PM, byron wallace <notifications@github.com>
wrote:

> Hmm I'm not sure that this is specific enough as stated. What do you mean
> OpenMEE "thinks" she has a contingency table? Can you please provide (1)
> the dataset in question, (2) the exact steps taken to reproduce the
> behavior in question, and (3) the expected behavior (in contrast to what
> occurs)? This way we can reproduce and address the issue. Thanks!
>
> On Sun, Jan 4, 2015 at 8:14 PM, JGurevitch <notifications@github.com>
> wrote:
>
> > I am working with someone who is using arsin square root proportions as
> > her effect size. It is nice that this is available in OpenMEE as an
> effect
> > size, but it doesn't make sense. She has data on the proportion of total
> > municipal waste that is food waste. So, she has 2 numbers: total tonnes
> of
> > waste, tonnes of food waste, and sample size, and wants to calculate the
> > arcsin square root proportion. OpenMEE thinks she has a 2X2 contingency
> > table (say what?) and then # events and sample size. This makes no sense
> to
> > me. It would be nice if it actually did allow one to calculate
> proportions,
> > the arcsin sq rt transformation, and then back transform the outcomes.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gdietz/OpenMEE/issues/162>.
> >
>
>
>
> --
> byron
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/162#issuecomment-68663824>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by gdietz** [comment]
Two issues happening here:
1. It doesn't make sense to group effects such a 'arcsine transformed proportion' as a 2x2 contingency table data type since they are only 1-arm proportions. We should add a new data type to the list for such effects which are only single arm.
2. We should make it possible to transform raw proportions into the the arcsine sqrt proportion via the Effect Size -> Transform effect size menu option.

Given this, i think it is still correct that we ask you to choose number of events and sample size, considering a proportion is
   # times something happens
----------------------------------------
   total number of observations

We need both these quantities to properly calculate effect size and variance before we can apply a transform. I assume your collegue already has effect sizes and variances?

**Comment by JGurevitch** [comment]
Proportions are not only number of events out of a total number of events.
They can also be amounts. The proportion that food waste is out of the
total amount of municipal trash was what we were looking at, in tons per
ton. So, proportions can be based on weight, area, length or any other
quantity, where you are interested in some fraction of the whole, whatever
the whole might be and however it is measured or counted. I didn't
understand the 'arm' thing, we don't use that terminology and I am not
clear what you meant.

On Sun, Mar 8, 2015 at 9:46 PM, George Dietz <notifications@github.com>
wrote:

> Two issues happening here:
> 1. It doesn't make sense to group effects such a 'arcsine transformed
> proportion' as a 2x2 contingency table data type since they are only 1-arm
> proportions. We should add a new data type to the list for such effects
> which are only single arm.
> 2. We should make it possible to transform raw proportions into the the
> arcsine sqrt proportion via the Effect Size -> Transform effect size menu
> option.
>
> Given this, i think it is still correct that we ask you to choose number
> of events and sample size, considering a proportion is
>  # times something happens
>
> total number of observations
>
> We need both these quantities to properly calculate effect size and
> variance before we can apply a transform. I assume your collegue already
> has effect sizes and variances?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/162#issuecomment-77788850>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bwallace** [comment]
I believe this is outside of the scope of an issue for the software at the moment.

**Comment by JGurevitch** [comment]
Yes, I agree. This has to be developed by people who understand the
probability theory well enough to do it.

On Mon, May 16, 2016 at 6:21 PM, byron wallace <notifications@github.com>
wrote:

> I believe this is outside of the scope of an issue for the software at the
> moment.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/162#issuecomment-219566150>
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
