### ISSUE TITLE
Generic effect sizes

### ISSUE THREAD

**Issue by JGurevitch** [gdietz/OpenMEE#164]
If you have a user-defined 'generic' effect size, the program won't recognize it as an effect size and use it in an analysis, until you click on "Change format" and choose "trans. effect" and for the variance, "trans. var". This is overly cryptic and unnecessary. If you choose "Generic effect" for the analysis, it should allow you to choose any column you wish without additional clicking around. "trans. effect" and "trans. var." are meaningless and completely opaque, and only serve to baffle the user. I am not sure why you have to click on anything to identify a continuous variable as an effect size or its variance, but if you really have to, call it "user-defined effect size" or something else more obvious and put that into the instructions on using the program.

**Comment by gdietz** [comment]
This is mainly done because we have a notion of effects on a 'transformed
scale' where effects of distributed symmetrically and on a raw scale where
they are not. I think removing this could inadvertently cause people to do
analyses on the wrong columns of data. I was also thinking somewhat along
these lines that maybe we should be less flexible with our columns. For
example, we have the user select in the beginning what kind of data they
have (binary or continuous) and then have them define what each column
actually is i.e. sample sizes, means, etc. somewhat like how how we do it
in OpenMetaAnalyst.

**Comment by JGurevitch** [comment]
I'm afraid I don't understand what you mean. More flexible is good. Less
flexible would be bad. Keep in mind that the needs of users in ecology are
different than and much more diverse than of those in medicine. I don't
know what you mean about the generic effect sizes.

On Sat, Jan 17, 2015 at 9:48 PM, George Dietz <notifications@github.com>
wrote:

> This is mainly done because we have a notion of effects on a 'transformed
> scale' where effects of distributed symmetrically and on a raw scale where
> they are not. I think removing this could inadvertently cause people to do
> analyses on the wrong columns of data. I was also thinking somewhat along
> these lines that maybe we should be less flexible with our columns. For
> example, we have the user select in the beginning what kind of data they
> have (binary or continuous) and then have them define what each column
> actually is i.e. sample sizes, means, etc. somewhat like how how we do it
> in OpenMetaAnalyst.
>
> On Sat, Jan 17, 2015 at 9:36 PM, JGurevitch <notifications@github.com>
> wrote:
>
> > If you have a user-defined 'generic' effect size, the program won't
> > recognize it as an effect size and use it in an analysis, until you
> click
> > on "Change format" and choose "trans. effect" and for the variance,
> "trans.
> > var". This is overly cryptic and unnecessary. If you choose "Generic
> > effect" for the analysis, it should allow you to choose any column you
> wish
> > without additional clicking around. "trans. effect" and "trans. var."
> are
> > meaningless and completely opaque, and only serve to baffle the user. I
> am
> > not sure why you have to click on anything to identify a continuous
> > variable as an effect size or its variance, but if you really have to,
> call
> > it "user-defined effect size" or something else more obvious and put
> that
> > into the instructions on using the program.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gdietz/OpenMEE/issues/164>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70394333>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bwallace** [comment]
This doesn't have to do with differences between ecology and medicine. We
need to know what scale numerical values are on so that we can deal with
them properly. Perhaps we could default to assuming that if the user
provides an effect, it is on the raw scale. George, under the hood you
could have this as the 'transformed' effect, and this could be basically
transparent to the user. Jessica, how does that sound?

I am not sure why you have to click on anything to identify a continuous
> variable as an effect size or its variance, but if you really have to, call
> it "user-defined effect size" or something else more obvious and put that
> into the instructions on using the program.


But then how could the program possibly know which columns are effect sizes
and associated variances?

On Sun, Jan 18, 2015 at 9:29 AM, JGurevitch <notifications@github.com>
wrote:

> I'm afraid I don't understand what you mean. More flexible is good. Less
> flexible would be bad. Keep in mind that the needs of users in ecology are
> different than and much more diverse than of those in medicine. I don't
> know what you mean about the generic effect sizes.
>
> On Sat, Jan 17, 2015 at 9:48 PM, George Dietz <notifications@github.com>
> wrote:
>
> > This is mainly done because we have a notion of effects on a
> 'transformed
> > scale' where effects of distributed symmetrically and on a raw scale
> where
> > they are not. I think removing this could inadvertently cause people to
> do
> > analyses on the wrong columns of data. I was also thinking somewhat
> along
> > these lines that maybe we should be less flexible with our columns. For
> > example, we have the user select in the beginning what kind of data they
> > have (binary or continuous) and then have them define what each column
> > actually is i.e. sample sizes, means, etc. somewhat like how how we do
> it
> > in OpenMetaAnalyst.
> >
> > On Sat, Jan 17, 2015 at 9:36 PM, JGurevitch <notifications@github.com>
> > wrote:
> >
> > > If you have a user-defined 'generic' effect size, the program won't
> > > recognize it as an effect size and use it in an analysis, until you
> > click
> > > on "Change format" and choose "trans. effect" and for the variance,
> > "trans.
> > > var". This is overly cryptic and unnecessary. If you choose "Generic
> > > effect" for the analysis, it should allow you to choose any column you
> > wish
> > > without additional clicking around. "trans. effect" and "trans. var."
> > are
> > > meaningless and completely opaque, and only serve to baffle the user.
> I
> > am
> > > not sure why you have to click on anything to identify a continuous
> > > variable as an effect size or its variance, but if you really have to,
> > call
> > > it "user-defined effect size" or something else more obvious and put
> > that
> > > into the instructions on using the program.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/gdietz/OpenMEE/issues/164>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70394333>.
> >
>
>
>
> --
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Jessica Gurevitch
> Professor
> Department of Ecology and Evolution
> Stony Brook University
> Stony Brook, NY 11794-5245 USA
> +1-631-632-8567
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70412317>.
>



-- 
byron

**Comment by JGurevitch** [comment]
Users who define their own effect sizes do so at their own risk. We can
have a pop up warning about this, but we can't control what they do. We can
even ask a couple of questions, such as, is the sampling variance normally
distributed? does this effect have to be transformed to meet the
assumptions of the analysis? etc. more as a warning/for educational value.
If they say "no" or "yes" then they can be blocked from proceeding with a
warning to get their act together before proceeding. You have to assume
that they are already normally distributed and treat them like you would d.
I don't see how you could do anything else if you are going to allow users
to define their own effect sizes.
The program doesn't have to know what column the effect sizes and their
variances are in, the user identifies this when doing the analyses.(The
program asks, "in what columns are the data located"? when you are in the
Analysis part).


On Sun, Jan 18, 2015 at 10:35 AM, byron wallace <notifications@github.com>
wrote:

> This doesn't have to do with differences between ecology and medicine. We
> need to know what scale numerical values are on so that we can deal with
> them properly. Perhaps we could default to assuming that if the user
> provides an effect, it is on the raw scale. George, under the hood you
> could have this as the 'transformed' effect, and this could be basically
> transparent to the user. Jessica, how does that sound?
>
> I am not sure why you have to click on anything to identify a continuous
> > variable as an effect size or its variance, but if you really have to,
> call
> > it "user-defined effect size" or something else more obvious and put
> that
> > into the instructions on using the program.
>
>
> But then how could the program possibly know which columns are effect
> sizes
> and associated variances?
>
> On Sun, Jan 18, 2015 at 9:29 AM, JGurevitch <notifications@github.com>
> wrote:
>
> > I'm afraid I don't understand what you mean. More flexible is good. Less
> > flexible would be bad. Keep in mind that the needs of users in ecology
> are
> > different than and much more diverse than of those in medicine. I don't
> > know what you mean about the generic effect sizes.
> >
> > On Sat, Jan 17, 2015 at 9:48 PM, George Dietz <notifications@github.com>
>
> > wrote:
> >
> > > This is mainly done because we have a notion of effects on a
> > 'transformed
> > > scale' where effects of distributed symmetrically and on a raw scale
> > where
> > > they are not. I think removing this could inadvertently cause people
> to
> > do
> > > analyses on the wrong columns of data. I was also thinking somewhat
> > along
> > > these lines that maybe we should be less flexible with our columns.
> For
> > > example, we have the user select in the beginning what kind of data
> they
> > > have (binary or continuous) and then have them define what each column
> > > actually is i.e. sample sizes, means, etc. somewhat like how how we do
> > it
> > > in OpenMetaAnalyst.
> > >
> > > On Sat, Jan 17, 2015 at 9:36 PM, JGurevitch <notifications@github.com>
>
> > > wrote:
> > >
> > > > If you have a user-defined 'generic' effect size, the program won't
> > > > recognize it as an effect size and use it in an analysis, until you
> > > click
> > > > on "Change format" and choose "trans. effect" and for the variance,
> > > "trans.
> > > > var". This is overly cryptic and unnecessary. If you choose "Generic
> > > > effect" for the analysis, it should allow you to choose any column
> you
> > > wish
> > > > without additional clicking around. "trans. effect" and "trans.
> var."
> > > are
> > > > meaningless and completely opaque, and only serve to baffle the
> user.
> > I
> > > am
> > > > not sure why you have to click on anything to identify a continuous
> > > > variable as an effect size or its variance, but if you really have
> to,
> > > call
> > > > it "user-defined effect size" or something else more obvious and put
> > > that
> > > > into the instructions on using the program.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/gdietz/OpenMEE/issues/164>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70394333>.
> > >
> >
> >
> >
> > --
> > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > Jessica Gurevitch
> > Professor
> > Department of Ecology and Evolution
> > Stony Brook University
> > Stony Brook, NY 11794-5245 USA
> > +1-631-632-8567
> > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70412317>.
> >
>
>
>
> --
> byron
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70412517>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bwallace** [comment]
I *think* you're agreeing with my proposed solution then: we just assume
that manually entered effects are on the 'raw scale' and inform the user
that this is what's happening.

On Sun, Jan 18, 2015 at 9:51 AM, JGurevitch <notifications@github.com>
wrote:

> Users who define their own effect sizes do so at their own risk. We can
> have a pop up warning about this, but we can't control what they do. We
> can
> even ask a couple of questions, such as, is the sampling variance normally
> distributed? does this effect have to be transformed to meet the
> assumptions of the analysis? etc. more as a warning/for educational value.
> If they say "no" or "yes" then they can be blocked from proceeding with a
> warning to get their act together before proceeding. You have to assume
> that they are already normally distributed and treat them like you would
> d.
> I don't see how you could do anything else if you are going to allow users
> to define their own effect sizes.
> The program doesn't have to know what column the effect sizes and their
> variances are in, the user identifies this when doing the analyses.(The
> program asks, "in what columns are the data located"? when you are in the
> Analysis part).
>
>
> On Sun, Jan 18, 2015 at 10:35 AM, byron wallace <notifications@github.com>
>
> wrote:
>
> > This doesn't have to do with differences between ecology and medicine.
> We
> > need to know what scale numerical values are on so that we can deal with
> > them properly. Perhaps we could default to assuming that if the user
> > provides an effect, it is on the raw scale. George, under the hood you
> > could have this as the 'transformed' effect, and this could be basically
> > transparent to the user. Jessica, how does that sound?
> >
> > I am not sure why you have to click on anything to identify a continuous
> > > variable as an effect size or its variance, but if you really have to,
> > call
> > > it "user-defined effect size" or something else more obvious and put
> > that
> > > into the instructions on using the program.
> >
> >
> > But then how could the program possibly know which columns are effect
> > sizes
> > and associated variances?
> >
> > On Sun, Jan 18, 2015 at 9:29 AM, JGurevitch <notifications@github.com>
> > wrote:
> >
> > > I'm afraid I don't understand what you mean. More flexible is good.
> Less
> > > flexible would be bad. Keep in mind that the needs of users in ecology
> > are
> > > different than and much more diverse than of those in medicine. I
> don't
> > > know what you mean about the generic effect sizes.
> > >
> > > On Sat, Jan 17, 2015 at 9:48 PM, George Dietz <
> notifications@github.com>
> >
> > > wrote:
> > >
> > > > This is mainly done because we have a notion of effects on a
> > > 'transformed
> > > > scale' where effects of distributed symmetrically and on a raw scale
> > > where
> > > > they are not. I think removing this could inadvertently cause people
> > to
> > > do
> > > > analyses on the wrong columns of data. I was also thinking somewhat
> > > along
> > > > these lines that maybe we should be less flexible with our columns.
> > For
> > > > example, we have the user select in the beginning what kind of data
> > they
> > > > have (binary or continuous) and then have them define what each
> column
> > > > actually is i.e. sample sizes, means, etc. somewhat like how how we
> do
> > > it
> > > > in OpenMetaAnalyst.
> > > >
> > > > On Sat, Jan 17, 2015 at 9:36 PM, JGurevitch <
> notifications@github.com>
> >
> > > > wrote:
> > > >
> > > > > If you have a user-defined 'generic' effect size, the program
> won't
> > > > > recognize it as an effect size and use it in an analysis, until
> you
> > > > click
> > > > > on "Change format" and choose "trans. effect" and for the
> variance,
> > > > "trans.
> > > > > var". This is overly cryptic and unnecessary. If you choose
> "Generic
> > > > > effect" for the analysis, it should allow you to choose any column
> > you
> > > > wish
> > > > > without additional clicking around. "trans. effect" and "trans.
> > var."
> > > > are
> > > > > meaningless and completely opaque, and only serve to baffle the
> > user.
> > > I
> > > > am
> > > > > not sure why you have to click on anything to identify a
> continuous
> > > > > variable as an effect size or its variance, but if you really have
> > to,
> > > > call
> > > > > it "user-defined effect size" or something else more obvious and
> put
> > > > that
> > > > > into the instructions on using the program.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/gdietz/OpenMEE/issues/164>.
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70394333>.
>
> > > >
> > >
> > >
> > >
> > > --
> > > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > > Jessica Gurevitch
> > > Professor
> > > Department of Ecology and Evolution
> > > Stony Brook University
> > > Stony Brook, NY 11794-5245 USA
> > > +1-631-632-8567
> > > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70412317>.
> > >
> >
> >
> >
> > --
> > byron
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70412517>.
> >
>
>
>
> --
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Jessica Gurevitch
> Professor
> Department of Ecology and Evolution
> Stony Brook University
> Stony Brook, NY 11794-5245 USA
> +1-631-632-8567
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70413120>.
>



-- 
byron

**Comment by JGurevitch** [comment]
Pretty much, yes.
I do like the idea of asking users a couple of questions (as I suggested)
to alert them to the fact that that they must pay attention to this.
Jessica

On Sun, Jan 18, 2015 at 11:02 AM, byron wallace <notifications@github.com>
wrote:

> I *think* you're agreeing with my proposed solution then: we just assume
> that manually entered effects are on the 'raw scale' and inform the user
> that this is what's happening.
>
> On Sun, Jan 18, 2015 at 9:51 AM, JGurevitch <notifications@github.com>
> wrote:
>
> > Users who define their own effect sizes do so at their own risk. We can
> > have a pop up warning about this, but we can't control what they do. We
> > can
> > even ask a couple of questions, such as, is the sampling variance
> normally
> > distributed? does this effect have to be transformed to meet the
> > assumptions of the analysis? etc. more as a warning/for educational
> value.
> > If they say "no" or "yes" then they can be blocked from proceeding with
> a
> > warning to get their act together before proceeding. You have to assume
> > that they are already normally distributed and treat them like you would
> > d.
> > I don't see how you could do anything else if you are going to allow
> users
> > to define their own effect sizes.
> > The program doesn't have to know what column the effect sizes and their
> > variances are in, the user identifies this when doing the analyses.(The
> > program asks, "in what columns are the data located"? when you are in
> the
> > Analysis part).
> >
> >
> > On Sun, Jan 18, 2015 at 10:35 AM, byron wallace <
> notifications@github.com>
> >
> > wrote:
> >
> > > This doesn't have to do with differences between ecology and medicine.
> > We
> > > need to know what scale numerical values are on so that we can deal
> with
> > > them properly. Perhaps we could default to assuming that if the user
> > > provides an effect, it is on the raw scale. George, under the hood you
> > > could have this as the 'transformed' effect, and this could be
> basically
> > > transparent to the user. Jessica, how does that sound?
> > >
> > > I am not sure why you have to click on anything to identify a
> continuous
> > > > variable as an effect size or its variance, but if you really have
> to,
> > > call
> > > > it "user-defined effect size" or something else more obvious and put
> > > that
> > > > into the instructions on using the program.
> > >
> > >
> > > But then how could the program possibly know which columns are effect
> > > sizes
> > > and associated variances?
> > >
> > > On Sun, Jan 18, 2015 at 9:29 AM, JGurevitch <notifications@github.com>
>
> > > wrote:
> > >
> > > > I'm afraid I don't understand what you mean. More flexible is good.
> > Less
> > > > flexible would be bad. Keep in mind that the needs of users in
> ecology
> > > are
> > > > different than and much more diverse than of those in medicine. I
> > don't
> > > > know what you mean about the generic effect sizes.
> > > >
> > > > On Sat, Jan 17, 2015 at 9:48 PM, George Dietz <
> > notifications@github.com>
> > >
> > > > wrote:
> > > >
> > > > > This is mainly done because we have a notion of effects on a
> > > > 'transformed
> > > > > scale' where effects of distributed symmetrically and on a raw
> scale
> > > > where
> > > > > they are not. I think removing this could inadvertently cause
> people
> > > to
> > > > do
> > > > > analyses on the wrong columns of data. I was also thinking
> somewhat
> > > > along
> > > > > these lines that maybe we should be less flexible with our
> columns.
> > > For
> > > > > example, we have the user select in the beginning what kind of
> data
> > > they
> > > > > have (binary or continuous) and then have them define what each
> > column
> > > > > actually is i.e. sample sizes, means, etc. somewhat like how how
> we
> > do
> > > > it
> > > > > in OpenMetaAnalyst.
> > > > >
> > > > > On Sat, Jan 17, 2015 at 9:36 PM, JGurevitch <
> > notifications@github.com>
> > >
> > > > > wrote:
> > > > >
> > > > > > If you have a user-defined 'generic' effect size, the program
> > won't
> > > > > > recognize it as an effect size and use it in an analysis, until
> > you
> > > > > click
> > > > > > on "Change format" and choose "trans. effect" and for the
> > variance,
> > > > > "trans.
> > > > > > var". This is overly cryptic and unnecessary. If you choose
> > "Generic
> > > > > > effect" for the analysis, it should allow you to choose any
> column
> > > you
> > > > > wish
> > > > > > without additional clicking around. "trans. effect" and "trans.
> > > var."
> > > > > are
> > > > > > meaningless and completely opaque, and only serve to baffle the
> > > user.
> > > > I
> > > > > am
> > > > > > not sure why you have to click on anything to identify a
> > continuous
> > > > > > variable as an effect size or its variance, but if you really
> have
> > > to,
> > > > > call
> > > > > > it "user-defined effect size" or something else more obvious and
> > put
> > > > > that
> > > > > > into the instructions on using the program.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <https://github.com/gdietz/OpenMEE/issues/164>.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70394333>.
> >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > > > Jessica Gurevitch
> > > > Professor
> > > > Department of Ecology and Evolution
> > > > Stony Brook University
> > > > Stony Brook, NY 11794-5245 USA
> > > > +1-631-632-8567
> > > > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70412317>.
>
> > > >
> > >
> > >
> > >
> > > --
> > > byron
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70412517>.
> > >
> >
> >
> >
> > --
> > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > Jessica Gurevitch
> > Professor
> > Department of Ecology and Evolution
> > Stony Brook University
> > Stony Brook, NY 11794-5245 USA
> > +1-631-632-8567
> > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70413120>.
> >
>
>
>
> --
> byron
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-70413524>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by gdietz** [comment]
Added a warning on the 'choose effect sizes wizard page' . The user is notified that the variance should be normally distributed and asked if they want to continue with the analysis.

**Comment by JGurevitch** [comment]
Excellent!

On Sun, Mar 8, 2015 at 8:16 PM, George Dietz <notifications@github.com>
wrote:

> Added a warning on the 'choose effect sizes wizard page' . The user is
> notified that the variance should be normally distributed and asked if they
> want to continue with the analysis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/164#issuecomment-77783998>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
