### ISSUE TITLE
include weighted histograms

### ISSUE THREAD

**Issue by gdietz** [gdietz/OpenMEE#168]
see forwarded email between Jessica and Fred Oswald from March 5, 2015 for details, sample code.

update: see email from May 23, 2015 for most recent version of code

**Comment by gdietz** [comment]
there are some issues with the same file Fred Oswald provided
-The weights should be inverse of variance not variance?
-'sev' not defined anywhere.

**Comment by bwallace** [comment]
I presume the newly circulated version addressed these?

**Comment by JGurevitch** [comment]
Somehow I don't think so but let's check
