### ISSUE TITLE
Cannot save file as .csv

### ISSUE THREAD

**Issue by vlangberg** [gdietz/OpenMEE#174]
Can import data from .csv, but can not save as a .csv.

**Comment by gdietz** [comment]
![export_csv](https://cloud.githubusercontent.com/assets/2617710/7341959/c589bdb0-ec79-11e4-8e10-6a3342b327b6.png)

@vlangberg : Yes we can!
- the arrow going into the box is CSV import
- the arrow going out of the box is CSV export

**Comment by vlangberg** [comment]
Is this possible in Open Meta Analyst?

**Comment by gdietz** [comment]
Are you sure you can't? There is an option to export CSV via them menu or
the box with an arrow coming out of it.

**Comment by vlangberg** [comment]
There is no box with an arrow coming out of it, and the "save as" option only allows .oma files to be saved.

**Comment by JGurevitch** [comment]
I believe you have to use "export".

On Mon, Jul 20, 2015 at 4:01 PM, vlangberg <notifications@github.com> wrote:

> There is no box with an arrow coming out of it, and the "save as" option
> only allows .oma files to be saved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/174#issuecomment-123011446>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by vlangberg** [comment]
I'll switch this issue over to the OMA page.
