### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by vlangberg** [gdietz/OpenMEE#180]
Multiple instances of the program are necessary if a user wants to work on multiple datasets.

**Comment by bwallace** [comment]
This is by design and we have no plans of changing this in the foreseeable
future.

On Wed, Apr 15, 2015 at 12:47 AM, vlangberg <notifications@github.com>
wrote:

> Multiple instances of the program are necessary if a user wants to work on
> multiple datasets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/180>.
>



-- 
byron
