### ISSUE TITLE
Importing from txt

### ISSUE THREAD

**Issue by vlangberg** [gdietz/OpenMEE#182]
Unable to copy/paste from a .txt file.

**Comment by bwallace** [comment]
What format, exactly? Do you mean tab-delimited? Can you provide an example file?

**Comment by gdietz** [comment]
I can copy into cells from a text file just fine, @vlangberg are you trying to copy some sort of csv text file into the table?

**Comment by vlangberg** [comment]
Here's is a video of what I was trying to do, and what went wrong:

https://vlangber.tinytake.com/sf/MTM4NzYxXzg3NTk2Ng

**Comment by bwallace** [comment]
It looks like it copied and pasted into the first column didn't it? You
were expecting it to recognize that this was tab-separated, perhaps? But
not even Excel does this.

On Wed, Jun 3, 2015 at 1:54 PM, vlangberg <notifications@github.com> wrote:

> Here's is a video of what I was trying to do, and what went wrong:
>
> https://vlangber.tinytake.com/sf/MTM4NzYxXzg3NTk2Ng
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/182#issuecomment-108574142>.
>



-- 
byron

**Comment by vlangberg** [comment]
So to use that .txt file in the video I'd have to import it or copy the numbers individually, correct?

**Comment by bwallace** [comment]
You can import it, yes

On Wed, Jun 3, 2015 at 2:17 PM, vlangberg <notifications@github.com> wrote:

> So to use that .txt file in the video I'd have to import it or copy the
> numbers individually, correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/182#issuecomment-108585556>.
>



-- 
byron

**Comment by bwallace** [comment]
This is exactly how Excel operates, I believe (not that Excel is a paragon
of UI.. but still... )

On Wed, Jun 3, 2015 at 2:39 PM, Byron <byron.wallace@gmail.com> wrote:

> You can import it, yes
>
> On Wed, Jun 3, 2015 at 2:17 PM, vlangberg <notifications@github.com>
> wrote:
>
>> So to use that .txt file in the video I'd have to import it or copy the
>> numbers individually, correct?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gdietz/OpenMEE/issues/182#issuecomment-108585556>.
>>
>
>
>
> --
> byron
>



-- 
byron

**Comment by gdietz** [comment]
@bwallace and @vlangberg We already have the importing csv functionality. We *could* do this too (recognize that a paste has some sort of structured data). I'm not sure how useful this would be and the assumptions we make about pasted-in data might open a can of worms. What do you think Byron? Maybe we should just close this.

**Comment by bwallace** [comment]
Nope I think we should just close this.

On Sun, Jun 7, 2015 at 10:34 PM, George Dietz <notifications@github.com>
wrote:

> @bwallace <https://github.com/bwallace> and @vlangberg
> <https://github.com/vlangberg> We already have the importing csv
> functionality. We *could* do this too (recognize that a paste has some
> sort of structured data). I'm not sure how useful this would be and the
> assumptions we make about pasted-in data might open a can of worms. What do
> you think Byron? Maybe we should just close this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/182#issuecomment-109849952>.
>



-- 
byron
