### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by vlangberg** [gdietz/OpenMEE#185]
Ctrl+z and the undo button do not always work.

**Comment by bwallace** [comment]
We need more information here. Can you describe the exact sequence of steps
to reproduce the problem please?

On Wed, Apr 15, 2015 at 12:56 AM, vlangberg <notifications@github.com>
wrote:

> Ctrl+z and the undo button do not always work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/185>.
>



-- 
byron

**Comment by gdietz** [comment]
@vlangberg +1 to Byron's comment. Undo doesn't come for free, we have to choose to include it. Letting us know where it doesn't work would be useful.

**Comment by vlangberg** [comment]
Changing the contents of a cell can't be undone.  For example, if I have all of my data entered and I accidentally clear a cell of data, ctrl+z does nothing.

**Comment by gdietz** [comment]
@vlangberg Can you describe the exact circumstances under which this is occurring? I need step by step instructions starting from 'launch the program'. Providing data files in the dropbox would be helpful too. I tried to replicate what you described above but when I clear a cell and then press ⌘-z (undo on mac), the original value returns.

**Comment by vlangberg** [comment]
Here is a video of the circumstances under which ctrl+z was not working:
https://vlangber.tinytake.com/sf/MTM4NzkzXzg3NjI0Nw

**Comment by gdietz** [comment]
Ah ok, this shouldn't be too hard to fix.

**Comment by gdietz** [comment]
I can't reproduce this so closing out.
