### ISSUE TITLE
Risk difference

### ISSUE THREAD

**Issue by vlangberg** [gdietz/OpenMEE#188]
This metric is incorrectly labeled as "rate difference."  Calculating the variance for this effect size sometimes incorrectly gives 0 variance.  The tau^2 value for analysis using risk difference is also incorrect.

**Comment by bwallace** [comment]
This seems like two separate issues. Could you please provide more details regarding tau^2; i.e., what do you mean this is incorrect? Can you provide example input, actual output and expected output? Thanks!

**Comment by gdietz** [comment]
@vlangberg Are you sure it's incorrectly labeleled? I think we talked to @JGurevitch at one point about this and in ecology its called Risk Difference. Also see here http://en.wikipedia.org/wiki/Attributable_risk.  *However, some epidemiologists use "attributable risk" when referring to the excess risk, also called the risk difference or rate difference.*

**Comment by JGurevitch** [comment]
Are you sure you talked to me about this? Ecologists don't use risk
difference, so, I am mystified.

On Sun, Apr 19, 2015 at 11:27 PM, George Dietz <notifications@github.com>
wrote:

> @vlangberg <https://github.com/vlangberg> Are you sure it's incorrectly
> labeleled? I think we talked to @JGurevitch
> <https://github.com/JGurevitch> at one point about this and in ecology
> its called Risk Difference. Also see here
> http://en.wikipedia.org/wiki/Attributable_risk. *However, some
> epidemiologists use "attributable risk" when referring to the excess risk,
> also called the risk difference or rate difference.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/188#issuecomment-94316726>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bwallace** [comment]
Alright, let's just change it to risk difference then. I thought Jessica had suggested Rate Difference at one point, as well, but I guess not!

**Comment by gdietz** [comment]
Yeah, i thought I got rate difference from the metawin manual

**Comment by bwallace** [comment]
George is correct. It is referred to as "rate difference" in MetaWin:

"A variety of commonly used meta-analysis effect sizes can be calculated,
including Hedges' d, response ratio, odds ratio, *rate difference*,
relative rate, and Fisher's ztransform (for details see Section 2.2.)"
http://people.biology.ufl.edu/osenberg/courses/Pitt/2003/Readings/Rosenberg%20et%20al%202000%20%28MetaWin%20v2%29.pdf

Jessica, do we still want to change this?

On Mon, Apr 20, 2015 at 8:46 PM, George Dietz <notifications@github.com>
wrote:

> Yeah, i thought I got rate difference from the metawin manual
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/188#issuecomment-94608954>.
>



-- 
byron

**Comment by JGurevitch** [comment]
Use whatever is most correct and whatever is most widely used in other
fields. People from other fields may be using OpenMEE, possibly.


On Tue, Apr 21, 2015 at 2:40 PM, byron wallace <notifications@github.com>
wrote:

> George is correct. It is referred to as "rate difference" in MetaWin:
>
> "A variety of commonly used meta-analysis effect sizes can be calculated,
> including Hedges' d, response ratio, odds ratio, *rate difference*,
> relative rate, and Fisher's ztransform (for details see Section 2.2.)"
>
> http://people.biology.ufl.edu/osenberg/courses/Pitt/2003/Readings/Rosenberg%20et%20al%202000%20%28MetaWin%20v2%29.pdf
>
> Jessica, do we still want to change this?
>
> On Mon, Apr 20, 2015 at 8:46 PM, George Dietz <notifications@github.com>
> wrote:
>
> > Yeah, i thought I got rate difference from the metawin manual
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gdietz/OpenMEE/issues/188#issuecomment-94608954>.
> >
>
>
>
> --
> byron
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/188#issuecomment-94777951>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by vlangberg** [comment]
I'm going to open a new issue to give more details about the tau^2 problem.

**Comment by chrishschmid** [comment]
A rate is defined as events/time (e.g. an incidence rate would be 5 events/year). Risk difference refers to a difference in proportions where the denominator is the number of individuals so it is #events per total at risk. So I would call a difference in proportions a risk difference which is the standard epidemiological and statistical term and reserve rate difference for a difference in rates (basically uses a Poisson distribution instead of binomial)
