### ISSUE TITLE
Tau^2 for Risk Difference

### ISSUE THREAD

**Issue by vlangberg** [gdietz/OpenMEE#189]
The data I am using is here: http://www.statsdirect.com/help/default.htm#meta_analysis/risk_difference.htm

According to this, the tau^2 value should be 0.111, but both OpenMEE and OMA report tau^2 to be 0.000 

![riskdifference](https://cloud.githubusercontent.com/assets/11543672/7257459/e6cab4f2-e823-11e4-9dee-e4284e6b321d.png)

**Comment by gdietz** [comment]
@vlangberg How did you get the 0.111 value?

**Comment by vlangberg** [comment]
My mistake, it should be 0.00011.  Is there any way to get the output to display more significant digits?

**Comment by bwallace** [comment]
That is a user setting in the 'preferences' dialog

On Wed, Apr 29, 2015 at 1:50 PM, vlangberg <notifications@github.com> wrote:

> My mistake, it should be 0.00011. Is there any way to get the output to
> display more significant digits?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/189#issuecomment-97538306>.
>



-- 
byron

**Comment by gdietz** [comment]
@vlangberg @bwallace

Created the dataset in question and added it to the dropbox folder. Note that the tau it calculates is 0.00011. As mentioned above, this was accomplished by setting the option in the user-preferences dialog.

![correct tau 2](https://cloud.githubusercontent.com/assets/2617710/7447903/2c87b5e4-f1d9-11e4-9e83-370df6d57798.png)
