### ISSUE TITLE
Variance for Risk Difference

### ISSUE THREAD

**Issue by vlangberg** [gdietz/OpenMEE#190]
OpenMEE is incorrectly reporting the variance of RD to be zero for some studies.  Here I am using the BCG data from the Borenstein book (and the metafor documentation).  OMA has no trouble calculating the variances and performing the meta-analysis for RD for this dataset.
OpenMEE error:
![variances](https://cloud.githubusercontent.com/assets/11543672/7257527/686729fa-e824-11e4-9dd8-5d977616d147.png)

Open Meta Analyst output for same data:
![omavariances](https://cloud.githubusercontent.com/assets/11543672/7257563/ae0dc8a6-e824-11e4-95ca-479885133a55.png)

**Comment by gdietz** [comment]
We seem to be erroneously rounding when the values are very tiny. Looking into it.
