### ISSUE TITLE
unit tests in R

### ISSUE THREAD

**Issue by bwallace** [gdietz/OpenMEE#193]
1. run a data exploration workflow --> does this work
2. test input/output somehow? 
3. brainstorm more?

**Comment by gdietz** [comment]
183160a726570fd3fceab453d5456db065e8a89c

**Comment by gdietz** [comment]
Basic utests for all analyses complete.

**Comment by JGurevitch** [comment]
That is excellent!

On Sun, Mar 6, 2016 at 11:46 PM, George Dietz <notifications@github.com>
wrote:

> Basic utests for all analyses complete.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/193#issuecomment-193096079>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
