### ISSUE TITLE
Meta-regression plot y-axis label

### ISSUE THREAD

**Issue by bwallace** [gdietz/OpenMEE#196]
Meta-regression plots should default to having the effect name on the y-axis.

**Comment by gdietz** [comment]
@bwallace Is this not already the case?
<img width="709" alt="screen shot 2016-06-12 at 10 25 42 pm" src="https://cloud.githubusercontent.com/assets/2617710/15995650/b683ba88-30ec-11e6-9933-4eeb4ae52d47.png">

**Comment by bwallace** [comment]
Yes I think I was using an old build. This looks good!
