### ISSUE TITLE
Hedges' d

### ISSUE THREAD

**Issue by vlangberg** [gdietz/OpenMEE#199]
For continuous data, effect size options are "Raw mean difference," "Hedges d," and "ln Response Ratio."  Hedges d doesn't exist, this should say "Hedges g," as this is the measure metafor uses.

**Comment by JGurevitch** [comment]
Ecologists have used "Hedges d" for decades. Yes, we know that in some
other disciplines it is called "Hedges g".

On Wed, Nov 11, 2015 at 9:34 AM, vlangberg <notifications@github.com> wrote:

> For continuous data, effect size options are "Raw mean difference,"
> "Hedges d," and "ln Response Ratio." Hedges d doesn't exist, this should
> say "Hedges g," as this is the measure metafor uses.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/199>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by JGurevitch** [comment]
One of the challenges and benefits of working in a multidisciplinary field
is that we sometimes have different terminology and sometimes genuinely
think differently. It's all good, though.

On Wed, Nov 11, 2015 at 9:34 AM, vlangberg <notifications@github.com> wrote:

> For continuous data, effect size options are "Raw mean difference,"
> "Hedges d," and "ln Response Ratio." Hedges d doesn't exist, this should
> say "Hedges g," as this is the measure metafor uses.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/199>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by gdietz** [comment]
So should we change it or stick with Hedges d?

**Comment by JGurevitch** [comment]
Please leave it as Hedges d, as this is the well-established usage in this
field. We need a users' manual that explains this and many other things!

On Sun, Nov 15, 2015 at 10:03 PM, George Dietz <notifications@github.com>
wrote:

> So should we change it or stick with Hedges d?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/199#issuecomment-156900496>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
