### ISSUE TITLE
Issue with correlation data

### ISSUE THREAD

**Issue by bwallace** [gdietz/OpenMEE#202]
From Rob (email: 1/14/15):
 
The problem occurs when I run a meta-analysis. Here I select standard meta-analysis. I soon appear on a screen that asks me “In what columns is the data located?”. As per previous instructions (an old email from one of you over a year ago) I keep the “Correlation” and the “Sample Size” drop down menus empty (see attached screenshot called “Locating data”). The reason for this is that if I put the correlation and sample size in these cells that I can never complete the meta-analysis because the option to choose a meta-analysis method does not appear on a later screen (see attached screenshot called “Analysis method” — notice that the dropdown menu is empty and I can’t proceed). In this instance I’ve used all default setting for the meta-analysis. You’ll notice that the forest plot (attached) uses z values instead of r values. This can be seen most clearly by looking at the three nonsense data points that I added to the bottom of the forest plot — the correlations are considerably greater than 1.0, which is impossible.

![analysis method](https://cloud.githubusercontent.com/assets/63118/12325033/049430da-ba8d-11e5-9eb0-6733b1ca6690.png)
<img width="686" alt="forestplot" src="https://cloud.githubusercontent.com/assets/63118/12325032/0493075a-ba8d-11e5-95ca-c245c7835204.png">
![locating data](https://cloud.githubusercontent.com/assets/63118/12325034/049459de-ba8d-11e5-8343-ccc3ef58ce66.JPG)

**Comment by gdietz** [comment]
This is the religiosity data set.

**Comment by gdietz** [comment]
@bwallace Reproduced the above. For the issue of the correlations being more than 1, i think this is just because Rob purposefully entered weird data for the last two rows?

**Comment by gdietz** [comment]
When choosing values for correlation and sample size, we get the following error:
```
changing size
populating combo box
we have raw data... parsing, parsing, parsing
Traceback (most recent call last):
  File "/Users/george/git/OpenMEE/common_wizard_pages/methods_and_parameters_page.py", line 62, in initializePage
    self.populate_cbo_box()
  File "/Users/george/git/OpenMEE/common_wizard_pages/methods_and_parameters_page.py", line 189, in populate_cbo_box
    one_arm=False)
  File "/Users/george/git/OpenMEE/python_to_R.py", line 677, in dataset_to_simple_cont_robj
    Ns1_col = data_location['experimental_sample_size']
KeyError: 'experimental_sample_size'
changing size
```

**Comment by gdietz** [comment]
dataset_to_simple_cont_robj() / ContinuousData R class has no facility to handle raw correlation (Zr) data well. Fix will be to just disable selection boxes of Correlation and sample size on data-location screen. This is OK since, we will have already used correlation and sample size to calculate the Zr.
