### ISSUE TITLE
Rename 'trans effect' and 'trans var' to 'user defined effect' and 'user defined var'

### ISSUE THREAD

**Issue by bwallace** [gdietz/OpenMEE#212]
Another suggestion from Jessica and Marc, again in the hopes of not confusing users.

**Comment by gdietz** [comment]
Isn't that losing some of the meaning then? How do we differentiate between effects on the log and non-log scale? 'user defined effect' doesn't really evoke that distinction.

**Comment by bwallace** [comment]
How about "user defined effect (transformed)" ?

On Tue, Apr 26, 2016 at 10:11 PM, George Dietz <notifications@github.com>
wrote:

> Isn't that losing some of the meaning then? How do we differentiate
> between effects on the log and non-log scale? 'user defined effect' doesn't
> really evoke that distinction.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/212#issuecomment-214958521>
>



-- 
byron

**Comment by gdietz** [comment]
sounds good to me.

**Comment by bwallace** [comment]
Fixed.
