### ISSUE TITLE
Disallow non-sensical predictors in meta-regressions

### ISSUE THREAD

**Issue by bwallace** [gdietz/OpenMEE#213]
In particular, do not allow people to select effects (the dependent variable..), variances, or sample sizes when performing a meta-reg

**Comment by gdietz** [comment]
Just doing effects for now. A sample size is a count of some quality which very well may be a valid covariate.

**Comment by bwallace** [comment]
seems reasonable.

**Comment by JGurevitch** [comment]
Yes, that seems fine to me as well. Thanks, this is great.

On Fri, Jun 10, 2016 at 9:45 AM, byron wallace <notifications@github.com>
wrote:

> seems reasonable.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/213#issuecomment-225185891>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGJ4uuvkSrpGRJLIe7Idu4RKJlTSSckMks5qKWqJgaJpZM4IQDZB>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jessica Gurevitch
Professor
Department of Ecology and Evolution
Stony Brook University
Stony Brook, NY 11794-5245 USA
+1-631-632-8567
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
